spring.application.name=exchange
spring.datasource.url=jdbc:postgresql://localhost:5432/exchange
spring.datasource.username=postgres
spring.datasource.password=loi123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update